### PR TITLE
using guard instead of if to get to task.results

### PR DESCRIPTION
**Pull request by anbarasu0504**

### CODE REVIEW

**Comment by yosuke-matsuda** [comment]
The use of `guard` is very appropriate here. We will consider updating all of the sample apps. Thank you.

**Comment by kvasukib** [comment]
Hi @anbarasu0504, Thanks for submitting a PR. Can you resolve the conflicts and re-submit?

**Comment by johndpope** [comment]
close this due to conflicts.

**Comment by minbi** [comment]
Thanks for the pull request. This is now out of date. We will try to capture this with any code refreshes.

**Pull request closed without merging**
